[package]
name = "driftwood"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pulldown-cmark = "0.11.0"
chrono = "0.4.38"
reqwest = { version = "0.12", features = ["blocking","json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] } 
serde_json = "1"
hyper = { version = "1", features = ["full"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }